### ISSUE TITLE
How to save and load trainable variables?

### ISSUE THREAD

**Issue by worasuch** [KristianHolsheimer/keras-gym#14]
I try to save trainable variables but cannot see the instruction in documentation website.
Could you suggest me to save and load trainable variables?

**Comment by KristianHolsheimer** [comment]
Apologies, I should really implement a nicer-looking interface for this. Here's an example that uses `keras` serialization to store/load a q-function:

```python
# store model weights periodically
if ep % 10 == 0:
    os.makedirs('checkpoints/', exist_ok=True)
    q.train_model.save_weights(f'checkpoints/train_model_{ep:08d}.h5')
    q.predict_model.save_weights(f'checkpoints/predict_model_{ep:08d}.h5')

# load model weights
from glob import glob
q.train_model.load_weights(max(glob('checkpoints/train_model_*.h5')))
q.predict_model.load_weights(max(glob('checkpoints/predict_model_*.h5')))
```

**Comment by worasuch** [comment]
Thank you very much for your help.

I try to understand your code example (Atari 2600: Pong with DQN)
Link of example code:
https://keras-gym.readthedocs.io/en/stable/notebooks/atari/dqn.html
However, I cannot clearly understand the fully connected output layer.

How many units does the output layer have?
And explain the details please.

In my opinion, there are 3 unit output layers which consist of Q(S,UP),
Q(S,DOWN) and  Q(S,STAY).
But I'm not sure.
[image: image.png]

Thanks in advance.

**Comment by KristianHolsheimer** [comment]
I see how that's confusing. A function approximator has a *body* and several *heads*, see code [here](https://keras-gym.readthedocs.io/en/stable/_modules/keras_gym/core/function_approximator.html#FunctionApproximator).

I believe that the Pong DQN agent uses `head_q2`. The forward pass is roughly `head(body(*inputs))`.
