### ISSUE TITLE
Enum3.4 not compatible with 3.6 and 3.8

### ISSUE THREAD

**Issue by candeira** [KristianHolsheimer/keras-gym#8]
Attempting an install of keras-gym in a python3.8 virtualenv (probably also on 3.6, but I haven't tried it) will result in an error

```
AttributeError: module 'enum' has no attribute 'IntFlag'
```

This is due to the enum34 module.

I'm filing it as a bug and not providing a patch, because it's up to project owner to make a decision:
- remove `enum34`, therefore removing support for Python versions <=3.4
- to support Python versions both <=3.4 and >3.4, substitute `python34` by `enum-compat`. This will isntall `enum34` only for older versions of python without stdlib enum.

(Also hi :wave:, I loved your talk at MLAI last Tuesday. Thanks for the great work!)

**Comment by KristianHolsheimer** [comment]
Thanks Javier,

Is there any reason you're not using python 3.6 or 3.7? Those are the versions I've set up for testing with Travis.

Also, IIRC tensorflow is only supported for python 3.6

Would you be able to try python 3.6?

**Comment by candeira** [comment]
Python3.8: My bad, really. I was just overeager, because I'm installing a ML rig from zero, so I wanted the latest stuff.

enum34: sorry.
